import { RoleEnum } from 'src/models/enums/role.enum';

export class AuthPayload {
  sub: string;
  email: string;
  role: RoleEnum;
  jti: string;
  exp?: number; // * This field will be auto-generated by the JWT service
}
