services:
  contest-system-db:
    image: postgres:16-alpine
    container_name: contest-system-postgres-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ~/docker-volumes/contest-system-db:/var/lib/postgresql/data
    restart: always
