services:
  contest-system-db:
    image: postgres:16-alpine
    container_name: contest-system-postgres-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./docker-volumes/contest-system-db:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: contest-system-redis-db
    image: redis:8.0-M02-alpine
    ports:
      - '${REDIS_BLACKLIST_PORT}:6379'
    volumes:
      - ./docker-volumes/redis-db:/data

volumes:
  redis-data:
    driver: local
